name: litgame_telegram
description: litgame-telegram
version: 0.0.1
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  teledart: ^0.1.3
  meta: ^1.2.4
  parse_server_sdk: ^2.0.1
  archive: ^2.0.13
  file: ^6.0.0-nullsafety.4
  dartis: ^0.5.0

dev_dependencies:
  test: ^1.15.7
  pedantic: ^1.9.2
