name: litgame_telegram
description: litgame-telegram
version: 0.0.1
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  teledart: ^0.1.1
  meta: ^1.2.4


dev_dependencies:
  test: ^1.0.0
